In [1]:
import oracledb
import pandas as pd

oracledb.init_oracle_client('C:\\Users\\KlimovaAnnaA\\Documents\\MyFiles\\Oracle\\instantclient_21_13')

In [2]:
connection = oracledb.connect(user="RISKCUSTOM", password="xxRiscRccess174!", host="exatest2-scan.moscow.eurochem.ru", port=1521, service_name='riskdev.moscow.eurochem.ru', disable_oob= True)

In [5]:
query = """SELECT * FROM "RISKACCESS"."sapPositionArrears" WHERE "reportDate" = TO_DATE('29/02/24', 'DD/MM/YY') AND "productType" in (130,131,132,133)"""
data = pd.read_sql(query, con=connection)

C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_3148\27959075.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data = pd.read_sql(query, con=connection)

In [6]:
data

,##batch_id,##deleted,##inserted,##origin_name,companyCode,companyName,valuationAreaId,valuationAreaName,valuationClassId,valuationClassName,...,reportDate_month,securedContractDate_year,securedContractDate_quarter,securedContractDate_month,termEnd_year,termEnd_quarter,termEnd_month,termStart_year,termStart_quarter,termStart_month
0,34099078@WHPROD,N,2024-02-29 07:13:33,SAP,E100,"АО ""Ковдорский ГОК""",001,Оперативная область оценки,0102,Финансовая кредиторская задолженность (долгоср...,...,2,NaN,NaN,NaN,2026,2,4,2021,2,4
1,34099078@WHPROD,N,2024-02-29 07:13:33,SAP,E100,"АО ""Ковдорский ГОК""",001,Оперативная область оценки,0102,Финансовая кредиторская задолженность (долгоср...,...,2,NaN,NaN,NaN,2026,2,5,2021,2,5
2,34099078@WHPROD,N,2024-02-29 07:13:33,SAP,E100,"АО ""Ковдорский ГОК""",001,Оперативная область оценки,0102,Финансовая кредиторская задолженность (долгоср...,...,2,NaN,NaN,NaN,2026,2,5,2021,2,5
3,34099078@WHPROD,N,2024-02-29 07:13:33,SAP,V100,"АО ""Енисейская ТГК""",001,Оперативная область оценки,0102,Финансовая кредиторская задолженность (долгоср...,...,2,NaN,NaN,NaN,2029,3,7,2023,2,4
4,34099078@WHPROD,N,2024-02-29 07:13:33,SAP,V100,"АО ""Енисейская ТГК""",001,Оперативная область оценки,0102,Финансовая кредиторская задолженность (долгоср...,...,2,NaN,NaN,NaN,2029,3,7,2023,2,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
792,34099078@WHPROD,N,2024-02-29 07:13:33,SAP,1R00,"ООО ""СГК""",001,Оперативная область оценки,0101,Финансовая кредиторская задолженность (краткос...,...,2,NaN,NaN,NaN,2033,1,3,2022,2,4
793,34099078@WHPROD,N,2024-02-29 07:13:33,SAP,1L00,МК «СУЭК ЛТД» (ООО),001,Оперативная область оценки,0242,Займы выданные (долгосрочные),...,2,NaN,NaN,NaN,2024,4,12,2021,1,1
794,34099078@WHPROD,N,2024-02-29 07:13:33,SAP,1100,"АО ""СУЭК""",001,Оперативная область оценки,0101,Финансовая кредиторская задолженность (краткос...,...,2,NaN,NaN,NaN,2031,4,12,2021,4,12
795,34099078@WHPROD,N,2024-02-29 07:13:33,SAP,1100,"АО ""СУЭК""",001,Оперативная область оценки,0101,Финансовая кредиторская задолженность (краткос...,...,2,NaN,NaN,NaN,2024,4,12,2020,1,1
796,34099078@WHPROD,N,2024-02-29 07:13:33,SAP,1100,"АО ""СУЭК""",001,Оперативная область оценки,0101,Финансовая кредиторская задолженность (краткос...,...,2,NaN,NaN,NaN,2024,3,9,2023,3,9